proxy-service/service.go

**Issue**
If a client sdk connected to the proxy in in-memory mode and had no segments configured we'd return a 404 for the `/client/env/:environment_uuid/target/:target/evaluations/:feature endpoint` which is fetched when the client sdk is fetching an update for a specific flag. 
**Fix**
Like the other functions in this file if we receive a `ErrCacheNotFound` error we just log it and continue because segments aren't required configuration we need to evaluate the flag.

(FFM-5106) Fix segments 404 error for client sdks

---

cmd/ff-proxy/main.go

The ff-proxy is hard configured to port 8000, in some installations this port may not always be available.
Added the ability to specify `--port` on the command line when starting the proxy service. If `--port` is not specified the port will default to 8000

Make port available as command line argument

---

Makefile

gocov-html released for the first time in 6 years and updated the package name which broke our test coverage reports, updating to use the new package name

(MAINT) Update gocov-html dep

---

Dockerfile

**Changes**
These ports are exposed by the pushpin section of the Dockerfile but they're not needed by consumers of the relay proxy so we can clean these up.
**Impact**
`EXPOSE` commands in a Dockerfile are really only there for documentation, they don't have any impact on which container ports are available once it runs. Having these hang around just means people will wonder why they're there and what they're used for so best to only expose our default running port for the proxy itself and have it be a bit cleaner when you run `docker ps`
**Old**
**New**

(FFM-5170) Cleanup exposed ports

---

go.mod
go.sum

**Change**
Bump golang.org/x/net version to resolve a vulnerability in that package
**Impact**
This remediates the only high vulnerability within the ff-proxy image

(FFM-5311) Fix net http vuln 

---

Dockerfile

This includes curl inside the image, which can be useful for testing, but is commonly used in healthchecks on AWS fargate and Docker images.

[FFM-5916]: Add curl to proxy to support healthchecks

---

cache/metrics.go
cache/metrics_test.go

**What**
- Cleans up the prometheus registration for the cache
- Puts a check in so we don't register CacheNotFound errors as errors in prometheus metrics. I think the error label in the prometheus should be reserved for internal/unexpected errors, we already track the status code in the http handlers so can see when requests have been made for a resource that doesn't exist
**Why**
I was a bit sloppy when initailly registering some of the metrics for the cache and spotted they weren't coming throuhg during my load testing.
**Testing**
Tested these changes out locally

FFM-7702 Clean up cache metrics registration

---

cmd/ff-proxy/main.go
domain/sdk_client_map.go
domain/sdk_client_map_test.go
go.mod
go.sum
proxy-service/service.go
stream/stream_worker.go
transport/encode_decode.go
transport/http_server.go
transport/http_server_test.go

**What**
- Updates the version of the go sdk we're using to one that has changes we need to implement this
- When the Proxy  receives a /stream request it checks if the internal SDK is connected to a SaaS stream
- Updates the stream worker so that if we receive a StreamDisconnect error from the SDK we close the stream between Proxy and SDK
- Moved the SDKClient from main to its own package and gave it public methods so we could inject it into the ProxyService
- We no longer mark the proxy as unhealthy if an internal sdk stream disconnects from SaaS
**Why**
There was an edge case where the Proxy could disconnect from SaaS stream and pull in updates via polling while it waited to reestablish the stream connection. Any changes pulled in via polling would be missed by SDKs listening for …

FFM-8024 Kill SDK streams if proxy disconnects from SaaS stream

---

cmd/ff-proxy/main.go
log/log.go
middleware/middleware.go
services/metric_service.go
transport/http_server_test.go

**What**
- Adds a middleware that logs out raw metrics payloads to help debug an issue being experienced by a customer
- There was a circular dependency issue with the log and middleware package which happened when I created the `NewMetricsLoggingMiddleware` function which is why I've moved the `RequestIDKey` type to the `log` package
- Just before the proxy sends metrics requests on to SaaS we now log the raw request body
**Testing**
- Running locally I can see the new log coming out
- Added this middleware to our tests and existing tests for our endpoints still pass
- Running locally with my debugger I can see the log coming out and the body is still being unmarshaled to the struct in the handler which means that we're resetting the request body properly in the middleware.
- When I …

FFM-8719 Log out raw metrics requests

---

go.mod
go.sum

Bump go sdk to 0.1.10 to pull in the error logging improvements

(FFM-8377) Bump go sdk to quiet error logs

---

cache/wrapper.go
cmd/ff-proxy/main.go
docs/configuration.md
log/log.go
middleware/middleware.go
services/admin_service_test.go
services/client_service_test.go
services/metric_service_test.go
transport/http_server_test.go

**What**
- Replaces `DEBUG` environment variable with `LOG_LEVEL`
- Removes a `value` field from a log statement in the cache wrapper
**Why**
- With the `DEBUG` environment variable we could only switch between logging at INFO or DEBUG level. Using `LOG_LEVEL` means we can now switch between INFO, ERROR or DEBUG
- The default logging level is `INFO` so we still output all the middleware logs by default and you have to opt in to disable debug logging. This is so we don't break functionality
for people expecting to see these logs.
- This `value` field that we were logging out dumps out all of the values in the logs e.g. if you have 10k flags it would log out 10k records which we don't want.
**Testing**
- Tested locally.

FFM-9095 Logging clean up

---

cache/wrapper.go
cache/wrapper_test.go
tests/e2e/stream_test.go

**What**
- Fixes a bug where we didn't recognise keys for individual
flags/segments
**Why**
- This was causing us to log errors whenever a flag was toggled on/off and not purge keys for individual
flags/segments
**Testing**
- Added unit tests

FFM-9163 Fix CacheWrapper invalid type flag error

---

cache/wrapper.go
go.mod
go.sum

**What**
- Updates the gosdk version
- Fixes CacheWrapper.getFeatureConfigs function. It turns out this function wasn't actually being called by the SDK code until I made the SDK changes. 
**Why**
- This version has a fix for a bug where we weren't updating the featureConfigs in the cache whenever we received an SSE event
**Testing**
- Locally
- Added unit tests to the GoSDK code that the Proxy relies on

FFM-9314 Update gosdk verison

---

config/remote/config.go
config/remote/config_test.go
domain/config.go
services/client_service.go
services/client_service_test.go
services/metric_service_test.go

**What**
- Adds a methods we need to the `ClientService` client for fetching config from the new endpoints
- Calls this method in the config code that gets called on startup
**Why**
- This fetches the config we need to populate the cache when the Proxy starts up
- In the next PR we can add the code to load this config into the cache

FFM-9466 Fetch config from SaaS on startup

---

cmd/ff-proxy/main.go
stream/sse.go
stream/stream.go
stream/stream_test.go

**What**
- Adds an optional onDisconnect function to the `Stream` type. This  gets called
whenever we exit the `Sub` method which happens any time we have a
stream connection that disconnects or if we fail trying to
connect/reconnect to the stream
- Adds a Backoffer to the `Stream` type. This defaults to one minute
**Why**
- If the SaaS -> Proxy stream disconnects we need to get the Proxy to
poll SaaS for changes to make sure it doesn't miss out on any. These
changes mean that if the SaaS -> Proxy stream disconnects we'll poll
every `backoffDuration` until the stream reconnects
**Testing**
- Unit tests
- Tested out locally

FFM-9620 Poll SaaS for changes when the stream disconnects

---

cmd/ff-proxy/main.go
domain/domain.go
domain/requests.go
health/health.go
proxy-service/service.go
stream/health.go
stream/on_connect_disconnect_handlers.go
transport/http_server_test.go

**What**
- Updates the health response so that it makes sense in the context of ProxyV2
- Added an extra poll for Config in the OnConnect handler for the Saas Stream. This will only happen if the previous stream state was disconnected
**Why**
- The current health response was ProxyV1 focused
- We poll for changes when the stream disconnects but there could be a minute between a disconnect an reconnect. If any changes were made in that minute we wouldn't have pulled them down when we reconnected
**Testing**
- Tested manually locally
- Update /health handler unit tests
- Found a /stream unit test that we could uncomment now that streaming is implemented

FFM-9888 Update Health response

---

cache/key_value_cache.go
cache/refresher.go
cache/refresher_test.go
config/local/config_test.go
config/remote/config_test.go
domain/repository.go
repository/auth_repo.go

**What**
- Fixes a logging typo where we were logging `failed to handle
addEnvironmentEvent` when we should have been logging `failed to
handle removeEnvironmentEvent`
- Bubbles up the domain.ErrCacheNotFound error to the cache refresher
and ignores logging/returning the error if we try to remove assets and
the key doesn't exist.
**Why**
- If I created an environment that had no segments and deleted it the
removeEnvironmentHandler would error out with this message because no
segments existed in the cache for it to remove. We probably don't want
to be logging this as a warning/error because it's valid for an
environment to exist with no segments,
```{"level":"warn","ts":"2023-11-15T09:40:03Z","caller":"stream/sse.go:52","msg":"failed to handle message","err":"failed to remove segment …
```

FFM-9931 Cleanup logging 

---

cache/refresher.go
cache/refresher_test.go
clients/client_service/client.go
cmd/ff-proxy/main.go
config/remote/config_test.go
domain/services.go

**What**
- Adds the cluster identifier to all requests that hit the ff client service
**Why**
- We should have had this in but missed it and got away with some stuff working because the routing on the LB was setup to always default to a certain cluster which meant we missed it until we tried doing tests against Prod1 & Prod2 which showed up some bugs

FFM-9957 Add cluster identifier to client service requests

---

tests/e2e/sdk_key_refreshing_test.go
tests/e2e/setup_test.go
tests/e2e/testhelpers/admin.go
tests/e2e/testhelpers/apikey.go
tests/e2e/testhelpers/platform.go
tests/e2e/testhelpers/project.go
tests/e2e/testhelpers/setup/.env.setup
tests/e2e/testhelpers/setup/main.go

**What**
- Adds e2e tests to test that when we create SDK keys in Saas they get
pushed down to the Proxy and can be used against the Proxy

FFM-10052 Add CreateSDKKey E2E tests 

---

clients/client_service/client.go
clients/client_service/client_test.go
clients/client_service/prometheus.go
cmd/ff-proxy/main.go
stream/prometheus.go

**What**
- Decoartes the generated ClientService implementation with a type that tracks the number of requests made to the client service and their duration
- Adds a subscription counter to the Stream Prometheus decorator. We can use this to graph /stream requests made from the Primary to Harness Saas
**Why**
- This is useful information to have to see if your Proxy is functioning Properly
- We can build dashboards off of this that we can share with customers to help them gain insight into how their Proxy is functioning
**Testing**
- Built a few panels for these new metrics locally and they seem to be working as expected

FFM-9943 Add prometheus metrics to client service requests

---

cache/key_value_cache.go
domain/errors.go
proxy-service/service.go
repository/auth_repo.go
repository/auth_repo_test.go
token/token_source.go
transport/encode_decode.go
transport/http_server_test.go

**What**
- If redis is down we now return a 500 status code for any /auth requests made to the Proxy
**Why**
- If redis is down we currently return a 401 from the auth handler. It turns out not all SDKs retry if they get a 401 but they should all retry if they get a 500. This resolves an issue where an SDK could fail to authenticate because redis was down and it received a 401 from the Proxy and never retried
**Testing**
- Manually tested locally
- Updated tests

FFM-10278 Return a 500 from the auth endpoint if we're unable to hit
